name: Fetch Sessions

on:
  workflow_dispatch:

jobs:
  fetch-sessions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Fetch session data
        run: pnpm start:ci
        env:
          BASE_URL: ${{ secrets.BASE_URL }}

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: sessions
          path: outputs/sessions.csv
          retention-days: 30
